[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.30-2/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200

; libssh2_esp dependency for SSH support
build_flags =
    -DLIBSSH2_MBEDTLS
    -DHAVE_LIBSSH2_H
    -DLIBSSH2_NO_ZLIB
    -DHAVE_CONFIG_H
    -DCONFIG_ARDUHAL_ESP_LOG
    -DCORE_DEBUG_LEVEL=3

lib_deps =
  symlink://..

; Use default partition table instead of huge_app.csv
; board_build.partitions = huge_app.csv
